print("My daily routine:")
print("1. I wake up at 10:00 AM.")
print("2. I brush my teeth, wash my face, and do my skincare routine.")
print("3. I either skip breakfast, or eat a small fruit.")
print("4. I go for a walk and Do my homework for my tuition class.")
print("5. I make sure to eat lunch at 1:00 PM, and I usually have a sandwich or a salad.")
print("6. After my homework, I take a shower and nap from 2:00 PM to 3:30 PM.")
print("The amount of hours between 2:00 PM and 3:30 PM is:", 3.5 - 2, "hours.")
print("7. When it reaches 4:00 PM, I Takes my tuition class.")
print("8. Tuiton class concludes at 6:00 PM, so i rest and pass time.")
print("9. My mother comes homes from work at 8:00 PM, so I have dinner with my family.")
print("10. I pass more time by reading a book or watching a movie unilt 12:00 AM")
print("11. I get ready for bed, and I usually go to sleep at 1:00 AM.")