name = input("Enter your name: ")
age = input("Enter your age: ")
city = input("Enter your city: ")
print("\n--- NAME TAG ---")
print("---------------")
print("Name:", name)
print("age:", age)
print("city:", city)
print("\nLoading. . .")